FROM cargo-build

WORKDIR /usr/src/diadro

COPY Cargo.toml .
COPY Cargo.lock .

COPY . /usr/src/diadro

RUN cargo build --target x86_64-unknown-linux-musl --release --offline
WORKDIR /usr/src/diadro/diadro
RUN ./build_web.sh

FROM scratch
COPY --from=cargo-build /usr/src/diadro/target/x86_64-unknown-linux-musl/release/dserver /dserver
COPY --from=cargo-build /usr/src/diadro/diadro/docs /docs
CMD ["/dserver", "/docs"]